apiVersion: v2
name: opal
description: A Helm chart for deploying the Opal server and a DataShield rock cluster.
type: application
home: https://opaldoc.obiba.org/en/latest/index.html
keywords:
  - DataShield
  - opal
  - obiba
sources:
  - https://github.com/obiba/opal
  - https://github.com/datashield/docker-rock
  - https://github.com/obiba/docker-opal
maintainers:
  - name: miracum
dependencies:
  - name: postgres
    version: 0.7.0
    repository: oci://registry-1.docker.io/cloudpirates
    condition: postgres.enabled
  - name: common
    repository: oci://ghcr.io/miracum/charts
    version: 0.1.1
kubeVersion: ">= 1.19.0"
version: 0.3.26
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cloudpirates-postgres/postgres
  # When using the list of objects option the valid supported kinds are
  # added, changed, deprecated, removed, fixed and security.
  artifacthub.io/changes: |-
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed and security.
    - kind: changed
      description: "Updated docker.io/curlimages/curl to sha256:935d9100e9ba842cdb060de42472c7ca90cfe9a7c96e4dacb55e79e560b3ff40"
